<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>TensorVisualBasicExamples</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TorchSharp-cpu" Version="0.103.0" />
  </ItemGroup>
</Project>
